version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=clustered_data_warehouse
    ports:
      - "3307:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  app-server:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clustered_data_warehouse?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "7070:7070"
    command: mvn clean spring-boot:run
    ports:
      - "7070:7070"
    restart: always
    depends_on:
      - db
    volumes:
      - ~/.m2:/root/.m2
      - .:/app